default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: health_travel_app_development

test:
  <<: *default
  database: health_travel_app_test

production:
  <<: *default
  database: health_travel_app_production
